### ISSUE TITLE
Limit animations to those which are necessary

### ISSUE THREAD

**Issue by CharlesBelov** [w3c/wai-presentations2all#16]
Some people are distracted or made ill by some animations. Avoid all unnecessary animations. In particular, do not slide in text or images.

**Comment by slhenry** [comment]
Notes for EOWG review:
* This resource doesn't cover every specific aspect of accessible presentations. It lists a few, and points to WCAG and other resources for more.
* If we were to add something to cover this point, we might use different wording. For example,
> Consider not using unnecessary motion or animations, such as text or images flying in from the side. Motion is particularly distracting for some people, and can make some people ill.

**Comment by slhenry** [comment]
Thanks @CharlesBelov for the input.

EOWG discussed this in our [13 Nov teleconference (minutes)](https://www.w3.org/2020/11/13-eo-minutes#item03).

EOWG wants to avoid the misconception that accessibility rules out all animation. In some cases, some kinds of animation could improve usability for all.

EOWG proposes the following text:
> **Consider how to use motion or animations**
> This includes text or images flying in from the side. Will the motion make the information easier to understand, or is it unnecessary? Certain types of motion can be particularly distracting for some people, and can make some people ill.

That text is  n context in this [preview page](https://deploy-preview-22--wai-presentations2all.netlify.app/teach-advocate/accessible-presentations/#consider-how-to-use-motion-or-animations). ([diff](https://github.com/w3c/wai-presentations2all/pull/22/files))

**Comment by bakkenb** [comment]
+1

**Comment by CharlesBelov** [comment]
Thank you. That seems like a clear way to put it and would address my concerns.

**Comment by eoncins** [comment]
+1

**Comment by AndrewArch** [comment]
+1 to EOWG suggestion

**Comment by daniel-montalvo** [comment]
+1

**Comment by Sylvie42** [comment]
+1

**Comment by lakeen** [comment]
+1

**Comment by kakinney** [comment]
+1

**Comment by vmmiller** [comment]
+1

**Comment by jasonbmckee** [comment]
+1

**Comment by slhenry** [comment]
merged https://github.com/w3c/wai-presentations2all/pull/22/files

**Comment by iadawn** [comment]
+1
