### ISSUE TITLE
add Expand All - Collapse All buttons at top

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-presentations2all#2]
like https://www.w3.org/WAI/training/accessible

**Comment by yatil** [comment]
Expand collapse buttons are not yet properly defined: w3c/wai-website-design#106

I plan to do something when I get back working on the theme again, but if there are any specific thoughts, it would be good to send them now.

**Comment by yatil** [comment]
Added in d26cbfb29fb67226d864005f6ea3d2cfc1541ae8
