### ISSUE TITLE
 guidelines for easy-to-read materials

### ISSUE THREAD

**Issue by eoncins** [w3c/wai-presentations2all#21]
@slhenry Apart from the font face maybe a link to a checklist could also be included. In addition, guidelines for easy-to-read materials could be provided.

Documents:

"Easy-to-read checklist: Checklist to make sure your document is easy to read"
https://www.inclusion-europe.eu/wp-content/uploads/2020/06/Easy-to-read-checklist-Inclusion-Europe.pdf

"Guidelines for easy-to-read materials" 
https://www.ifla.org/files/assets/hq/publications/professional-report/120.pdf

"EASIT project"
https://pagines.uab.cat/easit/en

**Comment by slhenry** [comment]
EOWG - please consider [criteria for what to include or not](https://github.com/w3c/wai-presentations2all/wiki/Criteria-for-what-to-include)

**Comment by slhenry** [comment]
In [20 Oct meeting](https://www.w3.org/2020/11/20-eo-minutes#item04), we decided that these resources have too much information that is not relevant to presentations.

@eoncins might propose some specific additions to our resource, such as for https://github.com/w3c/wai-presentations2all/issues/31
