### ISSUE TITLE
Keep distractions such as background noise to a minimum 

### ISSUE THREAD

**Issue by eoncins** [w3c/wai-presentations2all#24]
Maybe it would be good to mention background noise which might be a problem for the end users

"Keep distractions such as background noise to a minimum (avoid background music in the hall and in the conference room during breaks)"

**Comment by slhenry** [comment]
EOWG - please consider [criteria for what to include or not](https://github.com/w3c/wai-presentations2all/wiki/Criteria-for-what-to-include)

**Comment by lakeen** [comment]
+1

**Comment by slhenry** [comment]
+1s also in 20 November teleconference

**Comment by AndrewArch** [comment]
I wonder if we can relate this to WCAG 1.4.7 - Low or No Background Audio and instead say

"Keep distractions such as background noise to a minimum (background music in the hall and in the conference room during breaks is kept low or avoided)"

**Comment by eoncins** [comment]
+1 to mention relation to WCAG as stated by @AndrewArch

**Comment by shawna-slh** [comment]
I reviewed [Understanding Success Criterion 1.4.7: Low or No Background Audio](https://www.w3.org/WAI/WCAG21/Understanding/low-or-no-background-audio.html) and I think the detail on pre-recorded media makes it too complex and potentially confusing as a reference for this point for conferences and meetings.

For EOWG review: [draft pull request](https://deploy-preview-70--wai-presentations2all.netlify.app/teach-advocate/accessible-presentations/#planning-the-event-organizers) has under the "Planning the Event (organizers)" section:

> ### Limit distractions such as background noise _(in-person, remote)_
> Consider not having background music in the halls or conference rooms, including during breaks.

**Comment by shawna-slh** [comment]
[22 July 2022 EOWG minutes](https://www.w3.org/2022/07/22-eo-minutes#t08)

other types of distractions:
* pop-up notifications during presentation
* participant mobile phones buzzing
* visual distraction such window in meeting room with lots of action outside

**Comment by shawna-slh** [comment]
idea for further consideration:

> <h3>Limit audio and visual distractions  (in-person, remote)</h3>
> Consider not having background music in the halls or conference rooms, including during breaks. Or, keep the volume low.
> Ask participants to turn off mobile phones. Discourage side conversations.
> Try to avoid distractions such as catering setup during an active meeting or presentation. 

<hr>

questions:
1. How much space is this worth compared to other points?
2. OK combining audio and visual in one so it takes up less space? (also "distractions such as catering setup" is both audio and visual distraction)
3. These are kinda 3 separate paragraphs. All others are only 1 paragraph. Shall we put these all in one paragraph? Shall we delete some of the examples? Do we want to add more?

**Comment by shawna-slh** [comment]
[29 July 2022 EOWG Minutes](https://www.w3.org/2022/07/29-eo-minutes#item02)

some notes:
* "Limit audio and visual distractions" -> "Limit distractions"
* separate into relevant sections
* maybe note background audio (in Estella's words:)"nightmare for captioners", many people who are hard of hearing, ...

**Comment by shawna-slh** [comment]
see proposal with it covered in two places:
1. under [Planning the Event (organizers)](https://deploy-preview-83--wai-presentations2all.netlify.app/teach-advocate/accessible-presentations/#plan-to-limit-distractions-in-person-remote)
2. under [During the Presentation or Meeting (speakers)](https://deploy-preview-83--wai-presentations2all.netlify.app/teach-advocate/accessible-presentations/#limit-distractions-in-person-remote)

**Comment by JenniferChadwick** [comment]
+1

**Comment by sharronrush** [comment]
+1

**Comment by daniel-montalvo** [comment]
+1

**Comment by iadawn** [comment]
Broadly +1 with a couple of thoughts:

> For example, ask ... presenters to turn off system notifications.

I wonder how much this is an issue. Do remote presenting platforms manage this? Should it be mentioned as a consideration in platform selection?

> Discourage side conversations during meetings and presentations.

Remote meeting side chat can be more easily managed than audience members talking during a presentation. And that side chat in remote meetings can be extremely valuable. I wonder how much this strays into highlighting rude behaviour?

**Comment by beltonTPG** [comment]
+1

**Comment by shawna-slh** [comment]
> > For example, ask ... presenters to turn off system notifications.

> I wonder how much this is an issue. Do remote presenting platforms manage this? Should it be mentioned as a consideration in platform selection?

@vmmiller mentioned it in an EOWG telecon. I appreciated her providing the some examples of distractions. 

However, no one said that it was important to include. Personally, I've not had much of an issue with that in-person or remote. So likely it doesn't meet the [criteria to include]( https://github.com/w3c/wai-presentations2all/wiki/Criteria-for-what-to-include). So, I would be fine not including it. At the same time, there’s not much there currently:

> **Limit distractions**
> For example, ask participants to turn off mobile phone notifications, and presenters to turn off system notifications. Discourage side conversations during meetings and presentations.

Without it would be just:
> **Limit distractions**
> For example, ask participants to turn off mobile phone notifications. Discourage side conversations during meetings and presentations.

Which I think is fine.

_(as for platforms, we're not including such details, and instead pointing to [Selecting an accessible remote meeting platform](https://www.w3.org/TR/remote-meetings/#selection) in the TR Accessibility of Remote Meetings.)_

**Comment by shawna-slh** [comment]
>> Discourage side conversations during meetings and presentations.

> Remote meeting side chat can be more easily managed than audience members talking during a presentation. And that side chat in remote meetings can be extremely valuable. I wonder how much this strays into highlighting rude behaviour? I guess I am not sure on 'discourage'... how far does that go!

Personally, side conversations in in-person meetings are a significant accessibility issue for me.

In many cases, Zoom Chat is extremely distracting to screen reader users.

So I’m inclined to leave this – and let the situation dictate what 'discourage' means.

**Comment by shawna-slh** [comment]
> I also wondered how much of this can/should fall on the presenter.

Sure. Right now it’s in the section “During the Presentation or Meeting”, which applies to chairs/organizers, presenters, participants -- although that's not totally clear. Later draft heading is [Participants and Speakers: During the Meeting or Presentation](https://deploy-preview-86--wai-presentations2all.netlify.app/teach-advocate/accessible-presentations/#participants-and-speakers-during-the-meeting-or-presentation), though @MicheleAWilliams-A11y might be suggesting an edit to that?

**Comment by shawna-slh** [comment]
[survey responses](https://www.w3.org/2002/09/wbs/35532/Augustweekly/results#xq9)
