### ISSUE TITLE
interpreters

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-presentations2all#26]
in https://github.com/w3c/wai-presentations2all/issues/23 @eoncins says:
> I would avoid to use the term "interpreters" to include all professionals

See [proposed updated](https://deploy-preview-30--wai-presentations2all.netlify.app/teach-advocate/accessible-presentations/).

Main content now has:
> Arrange for good visibility of the speakers and interpreters
> Arrange for assistive listening devices (ALD)s, interpreters, and captioners, as needed
> Provide slides, handouts, and other material to participants, interpreters, translators, and captioners, as needed.
> Work with interpreters, translators, and captioners
> And avoid speaking too fast, so participants and sign language interpreters can better understand you and keep up.

Terminology section has:
>> interpreters
>> This includes sign language interpreters, cued speech transliterators, and others. Note that sign languages are different from spoken languages and there is not a one-to-one translation.

@eoncins , what do you suggest that we change?

**Comment by eoncins** [comment]
Maybe "Provide slides, handouts, and other material to participants and accessibility providers or professionals, as needed"

Terminology section: 
Accessibility providers or professionals 
These include language interpreters, captioners, speech-to-text interpreters, cued speech transliterators, audiodescribers and others. Note that sign languages are different from spoken languages and there is not a one-to-one translation.

**Comment by slhenry** [comment]
My take-aways from the [20 Nov meeting](https://www.w3.org/2020/11/20-eo-minutes#item03):
* EOWG would prefer to use specific words (interpreters, captioners) throughout the document, rather than using broader "Accessibility service providers or professionals" and needing to define it.
* In some regions, live simultaneous language translators are called _language interpreters_.

(fyi, background: We originally has just "sign language interpreters" in the main document, and no listing in the terminology section. Then someone said we needed to include "cued speech transliterators" so then we added the terminology listing.)

In the spirit of simplicity, I suggest:
* removing the couple mentions of language translators, since that's somewhat tangential to accessibility
* indicating the terminology is for *this resource only*, not necessarily a broad definition:

> **interpreters**
> In this resource, “interpreters” includes sign language interpreters, cued speech transliterators, and others. Note that sign languages are different from spoken languages and there is not a one-to-one translation.

<hr>

Feel free to re-open this issue if you have other input.
