### ISSUE TITLE
captions also-known-as subtitles for the deaf and hard of hearing

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-presentations2all#27]
in https://github.com/w3c/wai-presentations2all/issues/23 @eoncins says:

> It might be good also to include terminology from different regions such as captions (US) and Subtitles for the Deaf and Hard of Hearing (SDH).

**Comment by slhenry** [comment]
Added "subtitles for the deaf and hard of hearing" to:
> For example, provide captions (subtitles for the deaf and hard of hearing) and/or transcripts for audio, 

preview: https://deploy-preview-28--wai-presentations2all.netlify.app/teach-advocate/accessible-presentations/#make-media-fully-accessible--including-audio-and-video-used-in-sessions-and-recordings-of-sessions-provided-afterwards

**Comment by iadawn** [comment]
My understanding was that @eoncins comment was related to CART. This is not a thing in the UK certainly, and EU wide. The term more common in the UK is 'live captioning'.

Additionally, I am not sure that 'Subtitles for the Deaf and Hard of Hearing (SDH)' is a thing. Where the US has 'captions' the rest of the world has 'subtitles'. Although, 'captions' is becoming a little bit more common.

**Comment by slhenry** [comment]
Ah, OK, thanks, Kevin.

Interestingly, it looks like [SDH is also an American thing mostly related to presentation in DV](https://en.wikipedia.org/wiki/Subtitles#Subtitles_for_the_deaf_or_hard-of-hearing_(SDH))
(I started to add it to the Media Resource, then decided it's not an important term for web context, so didn't.)

I'll make a proposal for the live captioning and CART issue separately, and include link to captions and subtitle explanation.

I'm closing this issue.

**Comment by slhenry** [comment]
**_Updated Wednesday 18 November:_**<br>This proposed edit gets rid of "CART" in main document and weaves in explanation of some of the terms:
* **[diff showing changes](https://github.com/w3c/wai-presentations2all/pull/30/files)**
* **[preview with changes](https://deploy-preview-30--wai-presentations2all.netlify.app/teach-advocate/accessible-presentations/)**

**Comment by iadawn** [comment]
+1 

There were a few comments but I don't think they related to the way you have rewritten for CART
