### ISSUE TITLE
limit displayed text

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-presentations2all#31]
add something about it being hard to read and process lots of text and also listen to and process spoken information.

therefore, "slides" should usually have mostly bullet points with a few words, not long sentences.

**Comment by iadawn** [comment]
There may be a balance to be struck with this as too few words can leave Deaf and hard of hearing folks with little but the captions (which would of course be present) to focus on and if they miss a point there may not be enough on the slide to make sense of things.

**Comment by nitedog** [comment]
@iadawn actually I think that lots of text on slides would potentially distract from following the captions (as well as from following the audio).

**Comment by eoncins** [comment]
Sorry I think we are mixing up 2 things: 
One thing is the presentation layout: which might follow the 5x5, 6x6 rule or even the 7x7 rule and when possible if not always include easy-to-read/ easy-to-understand language.
And another issue is how this is presented to the endusers which might be an added problem is which if the speaker speaks too fast for instance, then end users can not convey information of the presentation and subtitles/captions regardless of their abilities.
To me the layout as @nitedog says is crucial.

**Comment by shawna-slh** [comment]
For EOWG review: [draft pull request](https://deploy-preview-71--wai-presentations2all.netlify.app/teach-advocate/accessible-presentations/#preparing-slides-and-projected-material-speakers) has under the "Preparing Slides and Projected Material (speakers)" section:

> ### Limit the amount of text and other content on slides _(in-person, remote)_

> It is difficult for many people to read text and listen to the speaker at the same time. Put limited content on the slides during a presentation, and consider providing more information in supporting material (such as a handout or slides with notes) for after the presentation.

**Comment by shawna-slh** [comment]
[22 July 2022 EOWG minutes](https://www.w3.org/2022/07/22-eo-minutes#t06)

all +1s

adding this under [Process for Minor Changes](https://www.w3.org/WAI/EO/wiki/EOWG_Participation_Info#Process_for_Minor_Changes)
