### ISSUE TITLE
Potential additional resource to add

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-presentations2all#60]
I noticed this page links to the ACM SIGACCESS "Accessible Conferences" page so just wanted to point out I helped create an updated version for "Virtual Conferences" that may also be helpful.

https://www.sigaccess.org/accessible-virtual-conferences/

**Comment by shawna-slh** [comment]
And <cite>Accessibility of Remote Meetings</cite> when published ([draft](https://w3c.github.io/apa/remote-meetings/))

**Comment by shawna-slh** [comment]
added.
