### ISSUE TITLE
consider additions for cognitive

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-presentations2all#77]
The resources already covers many cognitive issues.

these are general good practice, and moreso for cognitive:
* consistent design across slides
* start with overview, end with review of most important points

perhaps group them?

others to consider?

**Does this meet the [criteria for what to include or not](https://github.com/w3c/wai-presentations2all/wiki/Criteria-for-what-to-include) ?** Additionally cluttering this resource increases its cognitive load!

**Comment by shawna-slh** [comment]
[29 July 2022 EOWG minutes](https://www.w3.org/2022/07/29-eo-minutes#item06)

action: draft wording and provide pull request to see in context

**Comment by shawna-slh** [comment]
See proposed wording under **[Basics (for organizers & speakers)](https://deploy-preview-83--wai-presentations2all.netlify.app/teach-advocate/accessible-presentations/#coga2)**

**Comment by JenniferChadwick** [comment]
+1

**Comment by sharronrush** [comment]
+1

**Comment by vmmiller** [comment]
+1

**Comment by daniel-montalvo** [comment]
+1

**Comment by shawna-slh** [comment]
[survey results](https://www.w3.org/2002/09/wbs/35532/Augustweekly/results#xq9)
