### ISSUE TITLE
Provide multiple meeting connection methods (remote)

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-presentations2all#79]
fyi, from Remote Meetings TR doc:
> Provide participants with a variety of meeting connection methods (e.g. computer, app, telephone) to maximise accessibility and choice for participants with disabilities. This may also lead to additional in-meeting accessibility considerations (e.g. the need to live caption telephone participants).

draft for maybe under [Planning the Event](https://www.w3.org/WAI/teach-advocate/accessible-presentations/#planning-the-event-organizers)
### Provide multiple meeting connection options _(remote)_

Use a platform that allows participants to connect via computer, app, and/or telephone so they can use the method most accessible to them.

<hr>

Does this meet the [criteria for what to include or not](https://github.com/w3c/wai-presentations2all/wiki/Criteria-for-what-to-include) ?

**Comment by shawna-slh** [comment]
[29 July 2022 EOWG minutes](https://www.w3.org/2022/07/29-eo-minutes#item04)

A point made: This resources tells you what you need to do to make it accessible. It's not a standard. Don't "soften" too much. If something is required for accessibility, then say it. If a specific situation means they can't do it, so be it -- but they need to know it will be a limitation for some participants.

**Comment by shawna-slh** [comment]
@MicheleAWilliams-A11y were you going to take a pass at integrating this with your suggestions today?

**Comment by MicheleAWilliams-A11y** [comment]
Yes, thanks for tagging me so I won't lose it. It may create a larger revision than we want but let's see what I can come up with...

**Comment by shawna-slh** [comment]
Proposal: add it under [Ensure the remote meeting platform is accessible](https://deploy-preview-83--wai-presentations2all.netlify.app/teach-advocate/accessible-presentations/#ensure-the-remote-meeting-platform-is-accessible-remote) <- drafted there

**Comment by JenniferChadwick** [comment]
+1

**Comment by sharronrush** [comment]
+1

**Comment by lakeen** [comment]
+1

**Comment by vmmiller** [comment]
+1

**Comment by daniel-montalvo** [comment]
+1

**Comment by beltonTPG** [comment]
+1

**Comment by kakinney** [comment]
+1

**Comment by shawna-slh** [comment]
[survey results](https://www.w3.org/2002/09/wbs/35532/Augustweekly/results#xq9)
