### ISSUE TITLE
[for August] accessible formats, add PDF not

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-presentations2all#88]
Add: "PDF is not accessible to some participants with low vision or cognitive disabilities." to:

> **Format - Offer handouts, slides, and other material in accessible formats**
> Word processing formats are often the most flexible to meet different people's needs. PDF is not accessible to some participants with low vision or cognitive disabilities. Participants might need material in alternative formats such as large print or braille. If they get the material in advance electronically, they may not need it in hard copy.

**Comment by kakinney** [comment]
+1 to the addition

**Comment by hkramer** [comment]
Here's my crack at it:
Word processing formats are often the most flexible to meet different people's needs. Less flexible formats such as PDF is not accessible to some participants with low vision or cognitive disabilities because of limitations on changing font size, line spacing and other formatting. Participants might need material in alternative formats such as large print or braille. If they get the material in advance electronically, they may not need it in hard copy.

**Comment by iadawn** [comment]
Possible option

> Attendee material needs to be in a format that will support different people's needs. Some formats, such as PDF or protected Word documents, do not allow users to change the content, such as font size or colours, or all the content to be reflowed when  zoomed. Use formats that allow users to adapt the content to their needs, such as HTML or ePUB. This may also help participants who need material in alternative formats such as large print or braille.

**Comment by mpalmersg** [comment]
Some formats do not adequately support the needs of different people. For example, PDFs and other protected documents may restrict the users ability to change font size, colours or page zoom. Providing material in more accessible formats is preferred.

**Comment by daniel-montalvo** [comment]
As said before, I miss something along the lines of:

> PDF markup may not be exposed when using some screen readers, PDF readers, and operating systems.

Accessibility issues with PDF affect also screen reader users, despite the work that's put into tagging them!

**Comment by shawna-slh** [comment]
[19 August EOWG Minutes](https://www.w3.org/2022/08/19-eo-minutes.html#item01)

**Comment by shawna-slh** [comment]
Collecting resources that explain accessibility barriers even with tagged PDF:
* [Why GOV.UK content should be published in HTML and not PDF, Government Digital Service, 2018](https://gds.blog.gov.uk/2018/07/16/why-gov-uk-content-should-be-published-in-html-and-not-pdf/)
* [Support for Text Customization, TAdER.info, 2016](http://www.tader.info/support.html#PDFisNOTaccessible)

_Feel free to edit this comment to add others..._

**Comment by shawna-slh** [comment]
>PDF markup may not be exposed when using some screen readers, PDF readers, and operating systems.

I think @daniel-montalvo mentioned headings not available to Mac users.

Two questions:

1. Is there vetted documentation of this limitation (preferably from Apple, Adobe, &/or a blindness organization)?

2. Do we want to include this point here? Or, since the whole PDF-is-not-accessible is not a main point of the document, maybe keep it in mind for elsewhere?

_(Given its' already quite long -- see below -- I'd be inclined not to add it here.)_

If we do include the point, I think we want it less technical <grin>.

**Comment by shawna-slh** [comment]
Here's an updated draft based on EOWG meeting input. Note the context, first section under [Providing Accessible Material and Media](https://deploy-preview-86--wai-presentations2all.netlify.app/teach-advocate/accessible-presentations/#providing-accessible-material-and-media)

>**Format - Offer handouts, slides, and other material in accessible formats**
> Use formats that allow users to adapt the presentation to meet their needs, such as word processing, HTML, or EPUB. (Most users are more skilled at adapting word processing formats.)
> Avoid providing material only in formats that users cannot adapt, including PDF and protected Word documents. Tagged PDF is not accessible to users with low vision and cognitive disabilities who need to change font size, line spacing, colors, zoom, reflow, and print.
> Some participants will need print material in alternative formats such as large print and braille. If you give participants accessible digital material in advance, then you don’t usually need to provide these alternative print formats.

_and it's followed by_
> **Materials - Ensure slides, handouts, and other electronic material for participants is accessible**
...
> **Multimedia - Make media fully accessible, including audio and video used in sessions and recordings of sessions provided afterwards**
...

**Comment by bakkenb** [comment]
+1 to the language proposed by Shawn directly above.

**Comment by vmmiller** [comment]
+1 to Shawn's proposal above.

**Comment by daniel-montalvo** [comment]
> 1. Is there vetted documentation of this limitation (preferably from Apple, Adobe, &/or a blindness organization)?

Updated previous comment with info.

> 2. Do we want to include this point here? Or, since the whole PDF-is-not-accessible is not a main point of the document, maybe keep it in mind for elsewhere?
> 
> _(Given its' already quite long -- see below -- I'd be inclined not to add it here.)_
> 
> If we do include the point, I think we want it less technical .

+1 to not including this. But this is something we probably need to keep in mind for when referring to PDF screen reader accessibility.

**Comment by daniel-montalvo** [comment]
/me still thinks if we say

> ... Tagged PDF is not accessible to users with low vision and cognitive disabilities who need to change font size, line spacing, colors, zoom, reflow, and print.

We should also reference in some way the lack of semantic markup exposed in mac OS and other operating systems.

But I am happy to let this go if the majority of the group feels it's not needed.

**Comment by shawna-slh** [comment]
Added "significant exceptions for screen reader users" and references link. Note the context, first section under [Providing Accessible Material and Media](https://deploy-preview-86--wai-presentations2all.netlify.app/teach-advocate/accessible-presentations/#providing-accessible-material-and-media)

>**Format - Offer handouts, slides, and other material in accessible formats**
> Use formats that allow users to adapt the presentation to meet their needs, such as word processing, HTML, or EPUB. (Most users are more skilled at adapting word processing formats.) Avoid providing material only in formats that users cannot adapt, including PDF and protected Word documents. Even tagged PDF is not accessible to users with low vision and cognitive disabilities who need to change font size, line spacing, colors, zoom, reflow, and print; and has significant exceptions for screen reader users. _([references](https://github.com/w3c/wai-presentations2all/issues/88#issuecomment-1221003885))_

> Some participants will need print material in alternative formats such as large print and braille. If you give participants accessible digital material in advance, then you usually don’t need to provide these alternative print formats.

_and it's followed by_
> **Materials - Ensure slides, handouts, and other electronic material for participants is accessible**
...
> **Multimedia - Make media fully accessible, including audio and video used in sessions and recordings of sessions provided afterwards**
...

<hr>

_Note that EOWG decided we did need to put at least some explanation of why PDF is not accessible to some users, since "accessible PDF" is a common misunderstanding._

**Comment by daniel-montalvo** [comment]
+1

**Comment by bakkenb** [comment]
+1

**Comment by kakinney** [comment]
+1

**Comment by Sylvie42** [comment]
+1

**Comment by vmmiller** [comment]
+1

**Comment by shawna-slh** [comment]
implemented per EOWG resolution
