### ISSUE TITLE
Duplicate text under “Use sufficient color contrast”

### ISSUE THREAD

**Issue by drunken-monkey** [w3c/wai-presentations2all#9]
Under “Use sufficient color contrast” (“Preparing Slides and Projected Material (speakers)” section), after the “Refer“ in the second paragraph there follows a verbatim copy of the second half of the first paragraph. Apparently a mistake when editing?

I don’t know what it was meant to say, so can’t provide a PR.

**Comment by yatil** [comment]
@drunken-monkey Thanks for reporting this!

**Comment by slhenry** [comment]
ah, looks like this was taken care of a while ago, yet the issue not closed.

Thanks again for noting the issue!
