### ISSUE TITLE
[Mid] for this version, [Should address] for next -- Notes on mic placement instead of pointing to specific types of mics

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/wai-presentations2all#92]
> Remote: Usually built-in laptop microphones are not sufficient quality.

Generally, what creates a poor audio user experience is the mic not being close enough to the speaker's mouth.

Do we want to say something like "place the mic close enough to your mouth so that it picks your voice well" instead of pointing to built-in laptop mics? Any mic could sound bad if used inappropriately.

**Comment by shawna-slh** [comment]
Added:

> Ensure the microphone is positioned so it picks up your voice well. 

Deleted:

> _Remote:_ Usually built-in laptop microphones are not sufficient quality."

Since the checkpoint is "Use a good quality microphone", then this seems more clutter than important?

Note that "close to your mouth" applies to remote, but not usually in-person meetings. And, mic placement for in-person is important, too &mdash; maybe even more important.
