### ISSUE TITLE
[ED-low] Mention Preparation?

### ISSUE THREAD

**Issue by kakinney** [w3c/wai-presentations2all#93]
Should we mention allowing presenters time to prepare, or do a test run of their presentation?  So they can test things like their mic sound, video, and ability to share slides or presentation content?

**Comment by shawna-slh** [comment]
Initially I thought yes ... then thought that if there is a problem with those things, it's usually an issue for all participants, not particularly disproportionally for participants with disabilities. It is good practice for organizers to do (and Estella notes that most remote conferences do that). Yet, maybe not something to clutter this accessibility guidance? 

@kakinney What do you think? If you want more input from EOWG, please add Label "question". Or, if not, you can Close the issue.

**Comment by kakinney** [comment]
thanks for thinking it through and I agree, not something to clutter the guidance with.
