### ISSUE TITLE
Link to a Deploy Preview

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-presentations2all#94]
**Location:**
Under topic "Everyone: Understanding the Basics"...
In the "Benefits" section... after the example...

**Link error:**
The link in this sentence, "If you want to learn about more benefits of accessible media, see [Benefits to Organizations and Individuals, in Making Audio and Video Media Accessible]" tries to open the following deploy preview and throws an error... (https://deploy-preview-86--wai-presentations2all.netlify.app/media/av/#benefits)"

Not sure if this is an issue or just waiting for the deploy to be published. Just wanted to bring it up as I am checking links during approval review.

**Comment by shawna-slh** [comment]
HI @bakkenb Thanks for checking. Indeed, those types of links probably won't work on the preview. I've got an action item to check links when I publish it - a checkbox in https://github.com/w3c/wai-presentations2all/pull/86
